config:
  dockerfile: .woloxci/Dockerfile
  project_name: some-dotnet-project

  steps:
    # analysis:
    #   - bundle exec rubocop -R app spec --format simple
    #   - bundle exec rubycritic --path ./analysis --minimum-score 80 --no-browser
    # setup_db:
    #   - bundle exec rails db:create
    #   - bundle exec rails db:schema:load
    test:
      - dotnet test
    # security:
    #   - bundle exec brakeman --exit-on-error
    # audit:
    #   - bundle audit check --update

  environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    NUGET_XMLDOC_MODE: skip
    LANG: C.UTF-8

  timeout: 600
