config:
  dockerfile: .woloxci/Dockerfile
  project_name: wolox-lab-dotnet

services:
  - postgres
  - redis

steps:
  analysis:
    - dotnet --version
  setup_db:
    - dotnet --version
  test:
    - dotnet --version
  security:
    - dotnet --version
  audit:
    - dotnet --version

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
  LANG: C.UTF-8
