config:
  dockerfile: .woloxci/Dockerfile
  project_name: wolox-lab-dotnet

services:
  - postgres

steps:
  show_dotnet_version:
    - dotnet --version

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
