config:
  dockerfile: .woloxci/Dockerfile
  project_name: wolox-lab-dotnet

# services:
#   - redis

steps:
  analysis:
    - echo analysis
  setup_db:
    - echo setup db
  test:
    - dotnet test
  security:
    - echo security
  audit:
    - echo audit
    - sleep 10

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
  LANG: C.UTF-8

timeout: 600
